# Generated by Django 3.2.7 on 2021-09-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AscentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'AscentType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClimbedRoute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('belayer', models.CharField(blank=True, max_length=100, null=True)),
                ('suggested_grade', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'ClimbedRoute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClimbingDay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ClimbingDay',
                'managed': False,
            },
        ),
    ]
