# Generated by Django 3.2.7 on 2021-09-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('id_country', models.IntegerField()),
            ],
            options={
                'db_table': 'Crag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, max_length=70, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('consecutive_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'Sector',
                'managed': False,
            },
        ),
    ]
