# Generated by Django 3.2.7 on 2021-09-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slovenian_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'Country',
                'managed': False,
            },
        ),
    ]
